version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo "welcome nu00"
      - run: go test -v ./...
  artifacting:
    docker:
      - image: golang:1.10
    environment:
      - GH_USER: nu00
      - GH_EMAIL: xiangminli00@qq.com
    steps:
        - checkout
        - run: go test -v ./...
        - run:
            name: dummy artifacting
            command: |
              echo "hello artifact" > /tmp/hello-1
              mkdir /tmp/artifacts
              echo "world artifact" > /tmp/artifacts/hello-2;
        - store_artifacts:
            path: /tmp/artifacts/
            destination: world-2
        - store_artifacts:
            path: /tmp/hello-1
  deploy:
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - run: mkdir build
      - run: echo "deply hello" >> build/doc.txt
      - run: |
          git add -A
          git commit -m "hello deploy"

          git push origin master

workflows:
  version: 2
  build-1-2:
    jobs:
      - build
      - artifacting